lane :swiftgen do
  sh "cd ../Sources/PaywallReducer ; swiftgen config run --config swiftgen.yml"
  sh "cd ../Sources/Purchases ; swiftgen config run --config swiftgen.yml"
  sh "cd ../Sources/RateUsFeature ; swiftgen config run --config swiftgen.yml"
end
